In [61]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [62]:
data_raw = pd.read_csv('China_clean.csv')

In [63]:
years = data_raw.columns[1:]

In [64]:
indexes = data_raw['year']

In [66]:
data_raw.loc[0][1:]

1997   -21.9153
1998   -21.9527
1999   -22.0849
2000   -22.2037
2001   -22.2981
2002   -22.3897
2003   -22.4376
2004   -22.4231
2005   -22.4972
2006   -22.6003
2007   -22.6884
2008   -22.6884
2009    -22.762
2010   -22.8127
2011        NaN
2012        NaN
2013        NaN
2014        NaN
2015        NaN
2016        NaN
2017        NaN
Name: 0, dtype: object

In [67]:
data_clean = pd.DataFrame()
data_clean['years'] = years
data_clean.shape

(21, 1)

In [68]:
for it in range(len(indexes)):
    data = np.array(data_raw.loc[it][1:])
    label = data_raw.loc[it][0]
    data_clean[label]=data

In [69]:
data_clean

,years,BCI,CDI,CEH,CHI,DBI,DCI,DMI,DNI,DSI,...,SHI,SNM,SPI,TBG,TBN,TCL,TPI,USD,UWD,WWT
0,1997,-21.9153,-20.8831,NaN,-22.3779,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.0952,12.3829,9.775,NaN,NaN,NaN,NaN,NaN
1,1998,-21.9527,-20.9258,NaN,-22.4607,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.2669,12.4563,9.85635,NaN,NaN,NaN,NaN,NaN
2,1999,-22.0849,-21.0249,NaN,-22.541,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.5461,12.7751,9.96975,NaN,NaN,NaN,NaN,NaN
3,2000,-22.2037,-21.046,NaN,-22.6345,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11.1627,12.887,10.117,NaN,NaN,136.897,146.983,NaN
4,2001,-22.2981,-21.072,NaN,-22.6759,NaN,NaN,NaN,NaN,NaN,...,100,NaN,11.5613,13.3023,10.5395,0.141503,NaN,NaN,NaN,NaN
5,2002,-22.3897,-21.0822,NaN,-22.7301,NaN,NaN,NaN,NaN,NaN,...,99.92,NaN,11.822,13.6552,11.1157,0.147299,NaN,NaN,NaN,NaN
6,2003,-22.4376,-21.028,NaN,-22.7891,NaN,NaN,NaN,NaN,NaN,...,99.86,NaN,12.126,14.0495,11.4421,0.151814,NaN,NaN,NaN,NaN
7,2004,-22.4231,-20.9743,NaN,-22.8347,NaN,NaN,NaN,NaN,NaN,...,99.74,NaN,12.1427,14.0937,11.4675,0.190902,NaN,NaN,NaN,NaN
8,2005,-22.4972,-20.959,800.837,-22.9004,NaN,NaN,NaN,NaN,NaN,...,99.63,NaN,12.143,14.102,11.4807,0.199863,NaN,76.9299,88.6365,NaN
9,2006,-22.6003,-20.9758,798.889,-23.0014,-0.0466354,0.00531031,-0.0305775,-0.0425962,-0.0426322,...,99.49,NaN,12.2099,14.1022,11.481,0.242255,NaN,NaN,NaN,NaN
10,2007,-22.6884,-21.0185,770.018,-23.1218,NaN,NaN,NaN,NaN,NaN,...,99.3,NaN,12.2308,14.1034,11.4831,0.29188,NaN,NaN,NaN,NaN
11,2008,-22.6884,-21.0886,733.48,-23.2,NaN,NaN,NaN,NaN,NaN,...,99.03,NaN,12.2396,14.1066,11.4884,0.350402,NaN,NaN,NaN,NaN
12,2009,-22.762,-21.1072,724.173,-23.2766,NaN,NaN,NaN,NaN,NaN,...,98.85,NaN,12.2397,14.1084,11.4916,0.362454,NaN,NaN,NaN,NaN
13,2010,-22.8127,-21.1147,718.717,-23.3627,-0.0175828,NaN,NaN,NaN,-0.0165158,...,98.68,0.758297,12.2555,14.1084,11.4916,0.392466,NaN,35.1418,45.1823,NaN
14,2011,NaN,-21.1069,726.032,-23.456,NaN,NaN,NaN,NaN,NaN,...,98.52,NaN,12.2573,14.1084,11.4916,0.395334,NaN,NaN,NaN,NaN
15,2012,NaN,-21.1605,698.49,-23.5242,NaN,NaN,NaN,NaN,NaN,...,98.35,NaN,12.2576,14.1146,11.4925,0.389434,NaN,NaN,NaN,NaN
16,2013,NaN,-21.1891,678.799,-23.5918,NaN,NaN,NaN,NaN,NaN,...,98.24,NaN,12.2759,14.1146,11.4925,0.352976,NaN,NaN,NaN,NaN
17,2014,NaN,-21.2452,652.707,-23.6479,NaN,-0.017123,-0.0831897,-0.0823683,NaN,...,98.14,NaN,12.2759,14.1162,11.4952,0.344623,-0.0212509,NaN,NaN,NaN
18,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.1162,11.4952,0.327742,NaN,NaN,NaN,NaN
19,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.1179,11.5004,0.3425,NaN,21.0155,30.6689,16.128
20,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.1179,11.5004,NaN,NaN,NaN,NaN,NaN

In [81]:
data_new = data_clean
from sklearn import linear_model

In [100]:
for col in data_new.columns[1:]:
    notnull=(1-data_new[col].isnull()).astype(bool)
    print(notnull.sum())
    regr = linear_model.LinearRegression()
    years_available = data_new.years[notnull].reshape(-1,1)
    y = data_new[col][notnull]
    regr.fit(years_available,y)
    
    null = (1-notnull).astype(bool)
    years_null = data_new.years[null].reshape(-1,1)
    if len(years_null)==0:
        continue
    missing = regr.predict(years_null)
    
    data_new[col][null] = missing

14
18
10
18
2
2
2
2
2
2
18
19
5
18
18
18
14
5
4
8
8
20
14
14
1
18
21
21
16
1
4
4
1

C:\Users\rhythmswing\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """
C:\Users\rhythmswing\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  # Remove the CWD from sys.path while we load stuff.

In [105]:
data_new.to_csv

<bound method DataFrame.to_csv of    years      BCI      CDI      CEH      CHI         DBI          DCI  \
0   1997 -21.9153 -20.8831  924.096 -22.3779   -0.112004    0.0305478
1   1998 -21.9527 -20.9258  908.585 -22.4607   -0.104741    0.0277437
2   1999 -22.0849 -21.0249  893.075  -22.541  -0.0974775    0.0249395
3   2000 -22.2037  -21.046  877.564 -22.6345  -0.0902144    0.0221353
4   2001 -22.2981  -21.072  862.054 -22.6759  -0.0829512    0.0193312
5   2002 -22.3897 -21.0822  846.543 -22.7301  -0.0756881     0.016527
6   2003 -22.4376  -21.028  831.033 -22.7891  -0.0684249    0.0137228
7   2004 -22.4231 -20.9743  815.522 -22.8347  -0.0611617    0.0109186
8   2005 -22.4972  -20.959  800.837 -22.9004  -0.0538986   0.00811448
9   2006 -22.6003 -20.9758  798.889 -23.0014  -0.0466354   0.00531031
10  2007 -22.6884 -21.0185  770.018 -23.1218  -0.0393723   0.00250615
11  2008 -22.6884 -21.0886   733.48    -23.2  -0.0321091 -0.000298021
12  2009  -22.762 -21.1072  724.173 -23.2766   -0.024846  -0.00310219
13  2010 -22.8127 -21.1147  718.717 -23.3627  -0.0175828  -0.00590636
14  2011 -22.9255 -21.1069  726.032  -23.456  -0.0103197  -0.00871052
15  2012 -22.9941 -21.1605   698.49 -23.5242 -0.00305652   -0.0115147
16  2013 -23.0627 -21.1891  678.799 -23.5918  0.00420663   -0.0143189
17  2014 -23.1313 -21.2452  652.707 -23.6479   0.0114698    -0.017123
18  2015 -23.1999 -21.1885  644.906 -23.7266   0.0187329   -0.0199272
19  2016 -23.2685 -21.2025  629.396 -23.8024   0.0259961   -0.0227314
20  2017 -23.3371 -21.2165  613.885 -23.8781   0.0332592   -0.0255355

           DMI         DNI         DSI   ...        SHI       SNM      SPI  \
0    0.0286112  0.00214752   -0.101394   ...     100.78  0.758297  10.0952
1    0.0220347   -0.002824  -0.0948651   ...    100.623  0.758297  10.2669
2    0.0154582 -0.00779552  -0.0883359   ...    100.465  0.758297  10.5461
3   0.00888166   -0.012767  -0.0818068   ...    100.307  0.758297  11.1627
4   0.00230514  -0.0177386  -0.0752777   ...        100  0.758297  11.5613
5  -0.00427139  -0.0227101  -0.0687486   ...      99.92  0.758297   11.822
6   -0.0108479  -0.0276816  -0.0622195   ...      99.86  0.758297   12.126
7   -0.0174244  -0.0326531  -0.0556904   ...      99.74  0.758297  12.1427
8    -0.024001  -0.0376246  -0.0491613   ...      99.63  0.758297   12.143
9   -0.0305775  -0.0425962  -0.0426322   ...      99.49  0.758297  12.2099
10   -0.037154  -0.0475677  -0.0361031   ...       99.3  0.758297  12.2308
11  -0.0437305  -0.0525392   -0.029574   ...      99.03  0.758297  12.2396
12  -0.0503071  -0.0575107  -0.0230449   ...      98.85  0.758297  12.2397
13  -0.0568836  -0.0624822  -0.0165158   ...      98.68  0.758297  12.2555
14  -0.0634601  -0.0674538  -0.0099867   ...      98.52  0.758297  12.2573
15  -0.0700366  -0.0724253  -0.0034576   ...      98.35  0.758297  12.2576
16  -0.0766132  -0.0773968  0.00307151   ...      98.24  0.758297  12.2759
17  -0.0831897  -0.0823683  0.00960061   ...      98.14  0.758297  12.2759
18  -0.0897662  -0.0873398   0.0161297   ...    97.9426  0.758297  12.8776
19  -0.0963427  -0.0923114   0.0226588   ...     97.785  0.758297  12.9927
20   -0.102919  -0.0972829   0.0291879   ...    97.6273  0.758297  13.1079

        TBG      TBN        TCL        TPI       USD      UWD     WWT
0   12.3829    9.775  0.0970764 -0.0212509   145.405  156.397  16.128
1   12.4563  9.85635   0.113762 -0.0212509   138.158  149.092  16.128
2   12.7751  9.96975   0.130448 -0.0212509    130.91  141.787  16.128
3    12.887   10.117   0.147134 -0.0212509   136.897  146.983  16.128
4   13.3023  10.5395   0.141503 -0.0212509   116.416  127.177  16.128
5   13.6552  11.1157   0.147299 -0.0212509   109.168  119.872  16.128
6   14.0495  11.4421   0.151814 -0.0212509   101.921  112.567  16.128
7   14.0937  11.4675   0.190902 -0.0212509   94.6735  105.262  16.128
8    14.102  11.4807   0.199863 -0.0212509   76.9299  88.6365  16.128
9   14.1022   11.481   0.242255 -0.0212509   80.1789  90.6516  16.128
10  14.1034  11.4831    0.29188 -0.0212509   72.9315  83.3465  16.128
11  14.1066  11.4884   0.350402 -0.0212509   65.6842  76.0414  16.128
12  14.1084  11.4916   0.362454 -0.0212509   58.4369  68.7363  16.128
13  14.1084  11.4916   0.392466 -0.0212509   35.1418  45.1823  16.128
14  14.1084  11.4916   0.395334 -0.0212509   43.9422  54.1262  16.128
15  14.1146  11.4925   0.389434 -0.0212509   36.6949  46.8211  16.128
16  14.1146  11.4925   0.352976 -0.0212509   29.4476   39.516  16.128
17  14.1162  11.4952   0.344623 -0.0212509   22.2002  32.2109  16.128
18  14.1162  11.4952   0.327742 -0.0212509   14.9529  24.9059  16.128
19  14.1179  11.5004     0.3425 -0.0212509   21.0155  30.6689  16.128
20  14.1179  11.5004   0.430796 -0.0212509  0.458237  10.2957  16.128

[21 rows x 34 columns]>